### DISCUSSION TITLE
RFC: Visual editor for SQL queries

### DISCUSSION THREAD

**Discussion by Janpot** [mui/toolpad#2061] [Early feedback]
## Summary

Bring a simpler workflow to Toolpad for writing queries for postgres and MySql databases.

## Motivation

https://github.com/mui/mui-toolpad/issues/1952

## Design

<img width="422" alt="Screenshot 2023-05-24 at 10 40 42" src="https://github.com/mui/mui-toolpad/assets/2109932/9c6dd0b7-e1db-4cf7-81db-3917f9df591b">

Add another option when creating queries. Name it "PostgreSQL query". After choosing it, an editor opens, similar to the "HTTP request" one.

At the top the user can choose the PostgreSQL datasource in an autocomplete. If none is available, they get the option to create a new data source.

### Connection editor

A dialog for adding a postgres connection to Toolpad. In the file system, connection consists of two parts:
1. The connection definition in the resources folder:

    ```yml
    # resources/myPgConnection.yml
    kind: 'connection'
    apiVersion: '1',
    spec:
      kind: 'postgresql'
      connectionString: MY_PG_CONNECTION_STRING
      ssh: MY_PG_SSH_KEY
    ```

2. The .env file

    ```sh
    # .env
    MY_PG_CONNECTION=postgres://postgres:123456@127.0.0.1:5432/dummy
    MY_PG_SSH_KEY=...
    ```

The dialog presents fields for user/password/host/port/... and a "test connection" button. Hitting the "save" button stores all the parameters in the resource and .env files. We can give the option for choosing your own env variable name. We should always avoid overwriting existing env variables without prior user consent.

### query editor

All connections under resources that are of the `postgresql` kind are available in the connection dropdown. The query editor itself has a code editor for SQL queries and a preview table.

**parameter interpolation**

We could support mustache to inject parameters in SQL but with the following restrictions:

- Interpolations will be replaced with parameters `$0`, `$1` to avoid unwanted SQL injection. This means that 
    ```sql
    SELECT * FROM my_table WHERE my_table.column = {{mySelect.value}};
    ```
    first gets translated to
    ```sql
    SELECT * FROM my_table WHERE my_table.column = $0;
    ```
    and passed to the db as such. There will be no string replacement of interpolations in queries. i.e. we won't translate that into
    ```sql
    SELECT * FROM my_table WHERE my_table.column = "foo";
    ```
    **Note** this means that not all interpolation is possible. i.e. the following is invalid:
    ```sql
    SELECT * FROM {{myTableSelect.value}}
    ```

- the SQL query itself won't be available anywhere in the runtime on the browserside. The query is stored serverside and only parameters are transferred when executing it.

- The query gets stored in the page as 
```yml
    queries:
    - name: query1
      query:
        kind: postgres
        connection: myPostgres
        sql: |
          SELECT * FROM my_table WHERE my_table.column = $0;
      parameters:
        - name: $0
          value:
            $$jsExpression: |
              "query1_value"
```

To simplify an initial implementation, we could opt for starting out without mustache support and instead add a parameters section as in the pre-13 implementation.

The rest of the query works analog to the rest queries

## Trade-offs

- The mustache support may look like it gives you extra freedom, but it doesn't unlock anything that wasn't possible before with explicitly defined parameters. The queries will be harder to debug since what's running on the db will be different from what's in your text editor and the error messages won't always align with your expectations.
- 

## Alternatives

As an alternative we we could work towards a concept that is better integrated with the custom functions and which progressively allows _ejecting_ queries to code files
