### ISSUE TITLE
displayPrint on dashboardLayout Menu and AppBar

### ISSUE THREAD

**Issue by ebengtso** [mui/toolpad#4190]
### Summary

Elements of the DashboardLayout should not printed when the page is printed

I have tried to use the [`displayPrint`](https://mui.com/system/display/#display-in-print), but it is ignored.

```tsx
<DashboardLayout sx={{ displayPrint: 'none' }}>
  <Box sx={{m:1, displayPrint: 'block'}}>
    {children}
  </Box>
</DashboardLayout>
```

I have also tried to use a customClass, but in this case the space occupied by the dashboard menu and appbar turns to blank but occupies the space

```css
@media print {
  .print {
    visibility: visible;

  }
  .notprint {
    visibility: hidden;
  }
}
```

**Search keywords**: displayPrint, DashboardLayout
